coverage:
  status:
    project:
      default:
      target: auto
        threshold: 1%
        branches:
          - master
          - develop
      paths:
        - ^Converter.*
        - ^Mapper.*
        - ^ViewModel.*