apply plugin: "org.jetbrains.dokka"


dokka {
    dokkaPublications.html {
        outputDirectory.set(project.layout.buildDirectory.dir("javadoc"))
    }

    dokkaSourceSets.register("main") {
        // Source directories
        sourceRoots.from(file("src/main/kotlin"))
        sourceRoots.from(file("src/main/java"))

        sourceLink {
            localDirectory.set(file("src/main/kotlin"))
            remoteUrl.set(uri("https://github.com/infinum/android_dbinspector/"))
            remoteLineSuffix.set("#L")
        }

        jdkVersion.set(8)

        suppressObviousFunctions.set(true)
        suppressInheritedMembers.set(true)
        skipDeprecated.set(true)
        reportUndocumented.set(true)
        skipEmptyPackages.set(true)
        noStdlibLink.set(false)
        noJdkLink.set(false)
        noAndroidSdkLink.set(false)

        perPackageOption {
            matchingRegex.set("com\\.infinum\\.dbinspector\\.extensions.*")
            suppress.set(true)
        }
        perPackageOption {
            matchingRegex.set("com\\.infinum\\.dbinspector\\.domain\\.shared.*")
            suppress.set(true)
        }
        perPackageOption {
            matchingRegex.set("com\\.infinum\\.dbinspector\\.ui\\.shared.*")
            suppress.set(true)
        }
        perPackageOption {
            matchingRegex.set("com\\.infinum\\.dbinspector\\.sample.*")
            suppress.set(true)
        }
    }
}
